### ISSUE TITLE
FloatFFT.java

### ISSUE THREAD

**Issue by VibhavChaddha** [JorenSix/TarsosDSP#111]
Can anybody please explain to me how 'SPLIT_RADIX' is exactly working in FloatFFT.java. I am calling 'fft.realForwardFull(data)'. Gist will also work.
Thanks in advance.

**Comment by JorenSix** [comment]
Hi,

Please check the JTransforms documentation: [https://github.com/wendykierp/JTransforms](/wendykierp/JTransforms)
