### ISSUE TITLE
Mcleod Pitch Method (MPM) YIN and FastYIN implementations seem incomplete

### ISSUE THREAD

**Issue by j-funk** [JorenSix/TarsosDSP#113]
Hi, I was reading through the implementation of MPM here and noticed that MPM has a constant `DEFAULT_OVERLAP` which is never used. The same goes for YIN and FastYIN. When I grep the repo for this variable I find that it is only defined, never used.

```
	/**
	 * Overlap defines how much two audio buffers following each other should
	 * overlap (in samples). 75% overlap is advised in the MPM article.
	 */
	public static final int DEFAULT_OVERLAP = 768;
```

Though this implementation is definitely capable of providing a moderately accurate pitch result, it is not as robust as the papers suggest it should be and I frequently notice there are artifacts (usually octave errors).  I am curious how the overlap should be implemented as it is not implemented as part of the algorithm here.  If anyone knows, I would be very grateful.

**Comment by JorenSix** [comment]
Hi,

The default overlap can be used in setting up your processing chain. E.g. for MPM the paper suggests to use audio blocks of 1024 samples (sampled at 44.1kHz) and to use an overlap of 768 samples (75%). The ideal  parameters are dependent on the input (which instrument e.g.), the lowest/highest frequency you want to measure and the algorithm chosen. 

To get less octave errors you can either optimize these (and algorithm) parameters or look into e.g. pyin by matthias mauch.

Regards

Joren
