### ISSUE TITLE
STEREO processing - I would like to implement this feature - Help needed to jump start

### ISSUE THREAD

**Issue by Darlio** [JorenSix/TarsosDSP#210]
Hello,

I am a JAVA developer as well as a DJ in dance communities.

I would love to build a player / mixer around your library TARSOS ! But it only accepts MONO WAV inputs.

Would you agree that I try to make it process STEREO ones ? If so, do you have any clues on where to start digging ? I suppose I have to process the FLOAT arrays sent to FFT. But since you probably know your code very well, any clue on where to look for it ? A central place would be a great help !!!

--> be.tarsos.dsp.AudioDispatcher.java <--
Here it could be processing STEREO -> MONO so the sound of STEREO WAVs would not be a problem. Correct ?

Sorry for my english ! Best regards

**Comment by JorenSix** [comment]
Hi Darlio, 

That is indeed the place to look. The main thing that would need to be changed is the AudioEvent class which would then have more than one audio buffer (one for each channel). Please do fork and good luck with your project!
