### ISSUE TITLE
Pitch Detection in android

### ISSUE THREAD

**Issue by fraserjohnstone** [JorenSix/TarsosDSP#23]
Hi,

I Have been trying to incorporate this library (specifically pitch detection) into an android app, and I have run into a problem because of androids lack of support for the javax.sound.sampled package.

in the paper at http://0110.be/files/attachments/411/aes53_tarsos_dsp.pdf the process is outlined as:

audio - dispatcher - event - processor - output

but the dispatcher seems to rely heavily on the javax.sound.sampled package.

What would be the best way to load sound into one of the algorithms on android...possibly the AudioRecord, or AudioTrack class?

Fraser

**Comment by arunroyjhs** [comment]
Hi Joren 
Your API is really good . I just have one question . How can I use the dispatcher to calculate amplitude of the sound by the microphone . Is there some default function or we have to write some extra code for achieving this result 
Thanks in advance 
Regards 
Arunoday Ray

**Comment by JorenSix** [comment]
Hi,

In the AudioEvent object there are methods to find out about the energy (in dB) of the audio block. I think those are what you are looking for.

J

**Comment by arunroyjhs** [comment]
Hi Joren 
Thanks Joren for the response :) 
Yes I am looking for the Amplitude(db) of the sound which is being taken as input through the microphone . Which Function in the AudioEvent does give me Amplitude ?
Regard 
Arunoday Ray

**Comment by JorenSix** [comment]
Hi,

That would be getdBSPL() which i have just added to AudioEvent. Apparently it was private.

**Comment by arunroyjhs** [comment]
Can I access it from the Library I have or I need to download a new jar file ?

**Comment by JorenSix** [comment]
For the moment it is only in the github source. Tonight a new jar file will automatically appear on http://0110.be/releases/TarsosDSP/

**Comment by arunroyjhs** [comment]
Thank you Joren . 
One more query I have . When there is an interval of voice the API gives us some garbage value.
I am using this API with human Voice , when I just stop singing the API does not leave me on the last note sung but gives some other value .
Can there be some corrections ?

**Comment by arunroyjhs** [comment]
Hi Joren 
I am still waiting for the release of the new jar as my project requires the amplitude parameter .
Thank you 
regards 
Arunoday roy

**Comment by JorenSix** [comment]
Hi,

You can find them here: http://0110.be/releases/TarsosDSP/TarsosDSP-nightly/ or you could download the source and run the ant build script. That should produce the same results.

Regards

Joren

**Comment by JorenSix** [comment]
And about the pitch of speech/singing it seems to me that you could invent some kind of stability measure. If pitch is stable then it is singing otherwise speech?

**Comment by arunroyjhs** [comment]
Once again Thanx Joren .
it is for singing . It is stable when we start singing but when you just enter an interval or silence there occurs a garbage value

**Comment by amirfazel** [comment]
hi joren 
i wanna to use dispatcher from tarsos dsp and i try to programming thr example of github but it show me force close from app and in eclipse it show me error the the variable p is duplicate pls help me
Amir

**Comment by FireZenk** [comment]
Related question: Is it possible to use android AudioRecord when tarsos Pitchdetection is enabled?

**Comment by wilberninsiima** [comment]
I have a challenge when using the TarsosDSPAndroid in the android app, but the challenge is that i cannot differentiate if the microphone is connected or not

Because even if the microphone is disconnected, the audio is detected though having the low frequency

Hope to be helped on how to increase the sound pitch
