### ISSUE TITLE
License migration to Apache 2?

### ISSUE THREAD

**Issue by ohpauleez** [JorenSix/TarsosDSP#32]
Hi Joren - first and foremost, thank you for a fantastic library.  TarsosDSP + BoofCV are making the JVM a great place for computational challenges.

Is there any chance of migrating this to the Apache 2 License, to allow TarsosDSP and other libraries to be used together a little bit better?

**Comment by ceefour** [comment]
:+1: for this ! :)

**Comment by JorenSix** [comment]
Hi,

As can be seen in the readme there is a lot of code in TarsosDSP that is from various sources (mostly GPL'ed) which has been reworked (sometimes heavily) to function in a Java environment. For example there is a part of the GPL'd aubio project (an onset detector) translated from C. It makes sense to licence derivative code under the same licence as the original authors. As I see it TarsosDSP would not have been possible without these sources. Therefore, a license change is not going to happen.

Regards

Joren
