### ISSUE TITLE
 AudioDispatcherFactory.fromFloatArray for android

### ISSUE THREAD

**Issue by nolfwin** [JorenSix/TarsosDSP#33]
Hello,
Is it possible to create AudioDispatcher from the float array for android? Like the function  AudioDispatcherFactory.fromFloatArray that depends on javax.sound.*. I saw that there's only AudioDispatcherFactory.fromDefaultMicrophone for android. Is there a way to do this? Thank you very much.

**Comment by JorenSix** [comment]
Hi,

Sure, I has not been a priority for me but if someone ;-) would implement a `AudioDispatcherFactory.fromFloatArray ` and `AudioDispatcherFactory.fromFile `  for Android and send it to me in some form (a pull request is most practical)  then I would gladly add it to the project. If not, then perhaps I will implement it if I need this functionality or if I find the time one day.

Regards

Joren

**Comment by misrasaurabh1** [comment]
You should at least mention that this functionality is not available for android in the documentation. I spent a long time writing other code assuming this would work and now I am stuck.
