### ISSUE TITLE
AudioProcessor/WaveformWriter "overshoots" when buffer size is big

### ISSUE THREAD

**Issue by ceefour** [JorenSix/TarsosDSP#35]
I have a 67 MiB input WAV file.

Using 10 mibisamples (20 MiB) buffer, with direct dispatcher from file to `WaveformWriter`, I get a 80 MiB output. Not only larger than the original file, but also contains incorrect output, i.e. leftover audio from the previous block.

```java
final File sourceAudioFile = new File("/together/project_amanah/lumen/speech/expressive/dongeng-bangau.wav");
final File cloneAudioFile = new File("/together/project_amanah/lumen/speech/expressive/dongeng-bangau-clone.wav");
log.info("Cloning {} to {} ...", sourceAudioFile, cloneAudioFile);

// be careful with block size, since TersosDSP does "overshoot" samples
final AudioDispatcher dispatcher = AudioDispatcherFactory.fromFile(sourceAudioFile, 10 * 1024 * 1024, 0);
final TarsosDSPAudioFormat stdFormat = new TarsosDSPAudioFormat(44100, 16, 1, true, false);
dispatcher.addAudioProcessor(new WaveformWriter(stdFormat, cloneAudioFile.getPath()));
dispatcher.run();
```

I get a "more correct" output if I use a small buffer size, e.g. 2 kibisamples.

**Comment by ceefour** [comment]
Seems like `private AudioEvent.frameLength` is the correct number to use rather than `AudioEvent.getBufferSize()`.

However, there's no `getFrameLength()` ! So it's impossible to fix `WaveformWriter`

**Comment by JorenSix** [comment]
Hi, 

I have to review the audiodispatcher class and the whole processing pipeline. It can indeed go wrong on the first and last buffers. If these buffers contain only 1024 samples for example this is not the biggest problem (albeit a bit dirty). In your case these bugs really show. 

Also I have to review the consistency of naming of some elements (famesize, buffersize, bitdepth, ...) can sometimes be confusing. Over the years some elements were added that might not have followed the same nomenclature. The `AudioEvent` object is ready for a review also.

The `AudioDispatcher` and the processing pipeline also has trouble when the audio length changes during processing. The length of a buffer changes when pitch shifting, resampling and time stretching. Currently this works but is ugly. Also support for multi-channel audio is something on my TODO-list.

**Comment by ceefour** [comment]
I can understand if you wish to restructure.
However for the wave writer scenario a workaround would be good enough, and
wont break backward compatibility.
If you expose getFrameLength(), wave writer and newer processors which are
aware of it can use it, while existing processors can work as it was.

**Comment by JorenSix** [comment]
Sounds reasonable. I have added the getFrameLength().
