### ISSUE TITLE
write the output to a file on android

### ISSUE THREAD

**Issue by sinoohe** [JorenSix/TarsosDSP#37]
Hi,
I want to write the output of the dps processing on a file , but I couldn't find a way to do it.
There is a class named WaveformWriter on jvm.be.tarsos.dsp.io.jvm
How can I convert it to use in android? it uses javax.sound package which is not available on android.

**Comment by JorenSix** [comment]
Hi,

You would need to write the [header of a wave](http://www-mmsp.ece.mcgill.ca/documents/AudioFormats/WAVE/WAVE.html) file yourself followed by PCM samples ..

If you know the length of the file beforehand you can write the header immediately, otherwise you could write the number of samples in the header afterwards. E.g. using `RandomAccessFile.writeBytes`

**Comment by sinoohe** [comment]
Thank you
After searches I found a class in android speech ( https://android.googlesource.com/platform/frameworks/base.git/+/android-4.3_r2/core/java/android/speech/srec/WaveHeader.java )

now I have written a writer processor, I think others can also use it. can I send merge request for it?

**Comment by JorenSix** [comment]
Sure, more than welcome!

**Comment by hoangdado** [comment]
I had a problem with writing output audio in Android. Here is my code:
```
        new AndroidFFMPEGLocator(this);
        new Thread(new Runnable() {
            @Override
            public void run() {
                File externalStorage = Environment.getExternalStorageDirectory();
                File mp3 = new File(externalStorage.getAbsolutePath() , "/acapella.mp3");
                AudioDispatcher adp;
                adp = AudioDispatcherFactory.fromPipe(mp3.getAbsolutePath(),44100,2048,1024);

                adp.setZeroPadLastBuffer(true);

                adp.addAudioProcessor(new DelayEffect(0.2, 0.5, 44100));

                adp.addAudioProcessor(new AndroidAudioPlayer(adp.getFormat(),5000, AudioManager.STREAM_MUSIC));

                try {
                    File outputFile = new File(Environment.getExternalStorageDirectory(), "acapella_output.wav");

                    WriterProcessor writerProcessor = new WriterProcessor(adp.getFormat(), new RandomAccessFile(outputFile, "rw"));

                    adp.addAudioProcessor(writerProcessor);
                } catch (Exception e) {
                    Log.d(TAG, "Create WriterProcessor failed");
                    e.printStackTrace();
                }

                adp.run();
            }
        }).start();
```
The AndroidAudioPlayer and DelayEffect worked but the WriterProcessor didn't. I had set the WRITE_EXTERNAL_STORAGE permission and there was no log for writing error or success. 
How can I fix it?
