### ISSUE TITLE
MPM Pitchdetection

### ISSUE THREAD

**Issue by thnake** [JorenSix/TarsosDSP#42]
When I initialize the examplecode for pitchdetection with MPM, the algorithm does not react to notes below E2.  

int a = 1;
 AudioDispatcher dispatcher = AudioDispatcherFactory.fromDefaultMicrophone(22050,1024,0);
 dispatcher.addAudioProcessor(new PitchProcessor(PitchEstimationAlgorithm.MPM, 22050, a*1024, new PitchDetectionHandler() {...});

Increasing a (to increase buffer size) does not solve my problem. Do the unit tests succeed on lower pitches like 55 hz?

**Comment by JorenSix** [comment]
Hi, 

In the code above it seems that you only increase the buffer for the pitch detector and not for the audio itself:

    int a = 2;
    AudioDispatcher dispatcher = AudioDispatcherFactory.fromDefaultMicrophone(22050,__a*__1024,0);
    dispatcher.addAudioProcessor(new PitchProcessor(PitchEstimationAlgorithm.MPM, 22050, a*1024,  new PitchDetectionHandler() {...});

Could you try this and see if it helps?

**Comment by thnake** [comment]
Unfortunately it doen't do the trick. I wanted to test a different Frequency in PichDetectorTests.java but I have problems building the Library with AndroidStudio.

**Comment by JorenSix** [comment]
I will leave this open until I find some time to work on this...

**Comment by thnake** [comment]
In McLeodPitchMethod.java the  following definition is made:
private static final double LOWER_PITCH_CUTOFF = 80.0; // Hz
Lowering the threshold and using a sinewave below 80Hz works fine with the unittests. But I'm facing a problem using the Library in the project then. I get the following error:
Error:(42, 82) error: cannot access LineUnavailableException
class file for javax.sound.sampled.LineUnavailableException not found

**Comment by JorenSix** [comment]
Hi,

There should be no references to LineUnavailableException in an Android environment. The LineUnavailableException is not included in the android runtime (the rest of javax.sound.sampled is also not included) which explains this error. Make sure you are using the android TarsosDSP build.

**Comment by thnake** [comment]
Thanks a lot! Got it running now

**Comment by gauravapiscean** [comment]
Hello,
While I am running this in android, I am getting the following error.
java.lang.RuntimeException: Unable to start activity 

-> E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.

-> ComponentInfo{audio.admin.iot.fetchaudio/audio.admin.iot.fetchaudio.MainActivity}: java.lang.IllegalStateException: startRecording() called on an uninitialized AudioRecord.

-> Caused by: java.lang.IllegalStateException: startRecording() called on an uninitialized AudioRecord.

Any ideas on how to recover this?
