### ISSUE TITLE
AudioDispatcher error issue

### ISSUE THREAD

**Issue by amikhalev** [JorenSix/TarsosDSP#44]
If an AudioDispatcher is reading from a stream that can not keep up (eg. audioInputStream.read returns less than the requested number of bytes), and the AudioDispatcher is stopped, then there is a chance that (bytesToRead == totalBytesRead) is false and then AudioDispatcher will give an error like

```
The end of the audio stream has not been reached and the number of bytes read (1) is not equal to the expected amount of bytes(1024).
```

**Comment by JorenSix** [comment]
Hi,

Thanks for the bug report. Could you give an example of an audioInputStream that is not able to keep up with the dispatcher? In other words: can you make it clear how I can replicate the bug (and subsequently deal with it)? 

Thanks again!

**Comment by amikhalev** [comment]
In my case, I had an PipedInputStream being fed from another thread which was decoding audio from an MP3. This was then wrapped in a class implementing TarsosDSPAudioInputStream which just called all of the correct methods.

After looking at the source a bit more, I think I found a fix. It is in PR #46

**Comment by JorenSix** [comment]
After reviewing the code I fix will indeed work and will not cause a buffer of unexpected length to go through the pipeline since the pipeline is already stopped.

**Comment by JorenSix** [comment]
Should be fixed now.
