### ISSUE TITLE
License

### ISSUE THREAD

**Issue by alfahim** [JorenSix/TarsosDSP#49]
Hi, since the library is licensed under GPL, I have this basic question , am I allowed to add the jar file (without modification)  to my commercial closed Android app ?

**Comment by JorenSix** [comment]
Hi,

Thanks for the interest. I myself am not an IP rights specialist. TarsosDSP is GPL because it contains GPL'ed code as made clear in the readme. Please consult an expert.

Regards and good luck with your project!

Joren
