### ISSUE TITLE
How to implement TarsosDSP inside an android application

### ISSUE THREAD

**Issue by mehdifanai** [JorenSix/TarsosDSP#5]
Hi there
thanks for your great effort to develop such app.
I need to implement a low pass filter for the raw audio fetched from microphone input for android devices.Audio is fetched to a short array buffer.
How can i directly insert the buffer to the TarsosDSP  lowpass filter knowing that getaudiostream() is not available in android?

**Comment by himanshu1706** [comment]
hello mehdifanai, have you succeed to implement lowpass filter in your code. Please share the code of low pass filter process() method by which you are getting back processed float array.

**Comment by wilberninsiima** [comment]
Godd evenning sir, i have a challenge of auto detecting a microphone.
Once i open the developed application, the audio dispatcher still brings the pitch even if the external microphone is not connected.


And another thing is that: How can i set the delay time in miliseconds before the second result is gotten??
Best regards
Ninsiima wilber

**Comment by kipitsimple** [comment]
Very good work. I need a help. I am trying to find the formant frequencies(f0, f1, f2, f3), energy of a recorded wav ( Windows PCM) file of a single vowel in my android application, can you help me how to achieve that

**Comment by kipitsimple** [comment]
Using praat I can do the same and making my android application to contact the server for running praat script is ok, but I want to develop a standalone ad-hoc android application.

**Comment by kipitsimple** [comment]
Your prompt reply is highly appreciated... Thanks in advance.
