### ISSUE TITLE
Yeppp Library support for faster processing

### ISSUE THREAD

**Issue by jduke32** [JorenSix/TarsosDSP#50]
Hi , there is library named yeppp ,
its cross platform and there is java binding avalible.
It would be good if you add SIMD library support.

You can check the link below for more information:
http://www.yeppp.info

**Comment by JorenSix** [comment]
Hi,

Yeppp looks very interesting but one of the ideas behind TarsosDSP is to keep it as simple as possible. This means no external dependencies (except for a JRE/ART runtime) or platform dependent compilation steps (JNI bindings).

You are of course free to fork TarsosDSP and create a yeppp! enabled version!

Joren
