### ISSUE TITLE
Getting float array from a wav file

### ISSUE THREAD

**Issue by Priyadarshini-94** [JorenSix/TarsosDSP#52]
Hey,

I was trying to get float array from a recorded audio. I'm recording audio using the dispatcher. Here's what I'm doing. But it seems like it isn't working. Can you please help?

  public void record(){
        dispatcher = AudioDispatcherFactory.fromDefaultMicrophone(22050,1024,0);
        Toast.makeText(getApplicationContext(),
                " Recording",
                Toast.LENGTH_SHORT).show();
        dispatcher.addAudioProcessor(new AudioProcessor() {
            @Override
            public boolean process(AudioEvent audioEvent) {
                f = audioEvent.getFloatBuffer();
                text.setText(" "+f[0]+ " "+ f[10]);
                return false;
            }

            @Override
            public void processingFinished() {
                text.setText(" "+f[0]+ " "+ f[12]);
            }
        });
    }

**Comment by JorenSix** [comment]
Perhaps you still need to start the dispatcher: `new Thread(dispatcher).start();`? I would also not recommend to call user interface elements from another thread than the user interface thread.

Regards

Joren
