### ISSUE TITLE
changing audio playback rate but not pitch

### ISSUE THREAD

**Issue by yfsx** [JorenSix/TarsosDSP#53]
hey, thanks for giving us great app!
i have 2 questions so far.

1.  i've tried using SoundPool from android, but when i tried to slowing playback speed on one audio, the result is not only slower sound, but the pitch comes down too. is this library provides function to slowing down audio playback speed but not lowering its pitch?

2. i try compile 'com.github.JorenSix:TarsosDSP:TarsosDSPv2.2' but it seems not working. is there any gradle that works for android? 

thanks in advance!

**Comment by JorenSix** [comment]
Hi, 

For 1: see the time stretching example. It slows down playback without affecting pitch.

For 2: In Android Studio you can place TarsosDSP-Android-2.2.jar in the `app/libs` folder. By default Gradle includes this in the build. 

To check if this is the case, the following line should be included in the module app `build.gradle` file:

```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
}
```

You can download TarsosDSP releases from the [TarsosDSP release repository](http://0110.be/releases/TarsosDSP/TarsosDSP-2.2/)
