### ISSUE TITLE
Android Lib - Spectral Peak Processor

### ISSUE THREAD

**Issue by abhishekdewan101** [JorenSix/TarsosDSP#55]
Hi, 

I recently tried using your library to detect pitch and it works amazingly. However, I was having a bit of trouble trying to understand how to use the Spectral Peak Processor to get the fundamental frequency of the audio event. Could you please point me in the right direction. 

Thanks

**Comment by JorenSix** [comment]
Hi,

The Spectral Peak Processor determines how much energy there is in each frequency. It calculates two arrays: an array of frequencies and an array of magnitudes that correspond. Sometimes the fundamental frequency of an audio event corresponds to the frequency with the largest magintude. The following code should more or less work:

```java
final SpectralPeakProcessor spectralPeakFollower = new SpectralPeakProcessor(fftsize, overlap, sampleRate);
dispatcher = new AudioDispatcher(...);
dispatcher.addAudioProcessor(spectralPeakFollower);
dispatcher.addAudioProcessor(new AudioProcessor() {
	@Override
	public boolean process(AudioEvent audioEvent) {
		double[] magintudes = spectralPeakFollower.getMagnitudes();
		double[] frequencies = spectralPeakFollower.getFrequencyEstimates();
		//your code here
		return true;
	}

	@Override
	public void processingFinished() {
	
	}
});
dispatcher.run();
```

**Comment by abhishekdewan101** [comment]
Wow that worked thanks :D +1

**Comment by virux84** [comment]
Can you help me, with more detailed code for Android?
Thank you

**Comment by kjkrum** [comment]
This library was obviously written by and for DSP experts, but audio newbies like myself and others commenting here inevitably find a recommendation for it and then struggle to understand it. For example, I only know what to pass for `overlap` parameters by copying examples. I can read the code and see what operations are performed, but I don't know the purpose or meaning of the result. @JorenSix In your opinion, is this something that could be improved by documentation, or is there no alternative to a deep dive into the theory?

**Comment by pterodactylus42** [comment]
in case you want to do pitch detection, check this tutorial :-) : 

http://blog.form-follows-function.de/index.php?/archives/17-Frequenzerkennung-in-digitalen-Audiodaten-am-Beispiel-eines-Stimmgeraets.html

or another real good one by bjørn roche:

http://blog.bjornroche.com/2012/07/frequency-detection-using-fft-aka-pitch.html

bjørn mentions overlap as a must-do for good applications in pitch detection. generally, fft is one method that is good to look at if you start out into audio coding as pretty much stuff is based on it.

**Comment by kjkrum** [comment]
@pterodactylus42 I'm actually trying to estimate the volume of background noise when the signal has a known frequency range. Searching just leads me to dubious sound meter apps. :-/

**Comment by pterodactylus42** [comment]
audacity project has a noisegate:

https://github.com/audacity/audacity/blob/master/plug-ins/noisegate.ny

maybe this helps...
