### ISSUE TITLE
Question: Is it possible to mix/merge two audio files using TarsosDSP on Android?

### ISSUE THREAD

**Issue by kbalaguru** [JorenSix/TarsosDSP#56]
Is it possible to mix/merge (not concating ) two audio files using TarsosDSP on Android? 
Thanks.

**Comment by JorenSix** [comment]
The simple processing pipeline used in TarsosDSP is currently not designed to mix audio from multiple sources. However you can create an `AudioGenerator` that creates empty audio buffers and fill those buffers with audio from any source. In your case you would need to create an `AudioProcessor` that decodes a file from disk and mixes its contents with the audio buffer.

To create such `AudioProcessor`  see the `AudioDispatcher` for inspiration.

Good luck with your project!
