### ISSUE TITLE
Pitch detection error

### ISSUE THREAD

**Issue by mareklat** [JorenSix/TarsosDSP#57]
I am developing tuning app for Android and i want to get actual frequency from microphone. This library work very fast, but results are little diferent to the right frequency. 

I tested with this tool:
http://onlinetonegenerator.com/
When i set:
440 Hz, library return ~440,3 Hz
880 Hz, return ~ 880,7 Hz
1750 Hz, return ~ 1752,1 Hz

Testing with piano:
http://www.play-the-piano-online.com/piano-keyboard-fun-for-all
Error is x2 bigger than in the case with generator. 

Errors is always bigger than real frequency, not smaller. I tested with many devices and results are the same.
I use FFT_YIN algorithm. Buffor and sample size changes not helping - results are the same. 

What is the reason and how can I fix this?

Sorry for my Google Translator english :)

**Comment by JorenSix** [comment]
Hi, 

I'm not sure which application you are developing that needs such precise pitch estimations. The error is well within the difference in pitch that humans can discern. Going from 880Hz to 880.7Hz is a difference of 1.3 cents. Humans are able to tell the difference (more or less) between two tones if the difference is at least 6 cents.

Rounding errors, limited block size of an fft, windowing, ...all amount to those small errors.

Good luck with your project!

**Comment by mareklat** [comment]
I am developing piano tune app and precision is required. 
You're right. I need to focus on reducing errors by using these techniques.

Ok, thank you for your time!
