### ISSUE TITLE
Can I get bytebuffer after lowpassfs filter processing?

### ISSUE THREAD

**Issue by himanshu1706** [JorenSix/TarsosDSP#60]
Hello, I am using TarsosDSP for implementing the filters on my recorded audio buffer in my android app.I am using below code for that

                    final TarsosDSPAudioFormat format = new TarsosDSPAudioFormat(44100, 16, 1, true, false);
                    
                    final AudioFloatConverter converter = AudioFloatConverter
            				.getConverter(format);
                    
            		final byte[] byteBuffer = new byte[mFloatBuffer.length
            				* format.getFrameSize()];
            		
            		converter.toByteArray(mFloatBuffer, byteBuffer);
            		
            		final ByteArrayInputStream bais = new ByteArrayInputStream(byteBuffer);
            		
            		AndroidAudioInputStream inputStream = new AndroidAudioInputStream(bais, format,
            				mFloatBuffer.length);
            		
            		final AudioDispatcher dispatcher = new AudioDispatcher(inputStream,
            				1024, 0);
            		dispatcher.addAudioProcessor(new LowPassFS(1000, 44100));
            		dispatcher.addAudioProcessor(new HighPass(100, 44100));
            		dispatcher.addAudioProcessor(new WaveformWriter(format, "test.wav"));
            		dispatcher.run();
But I am facing issue with WaveformWriter() object as it is importing javax.sound. classes which is not available for android. But I am thinking that what if I can get only processed buffers after applying LowPassFS instead of written .wav file. Can you guide me to achieve this.

**Comment by JorenSix** [comment]
Hi, There is also the `WriterProcessor` class that can be used for the same task and does not depend on `javax.sound*`.

Regards Joren
