### ISSUE TITLE
Pitch Shifting Example in Android

### ISSUE THREAD

**Issue by kosmologist** [JorenSix/TarsosDSP#64]
I'm writing an android app in which i've to shift pitch of a source file and save it to target file. I've almost ported the Java code given below to Android except the WaveformWriter class which is used in audioDispatcher as a audioProcessor.

This is the Java code example of Pitch Shifting (copied from tarsosDSP examples)
File inputFile = new File(source);
		AudioFormat format = AudioSystem.getAudioFileFormat(inputFile).getFormat();	
		double sampleRate = format.getSampleRate();
		double factor = PitchShiftingExample.centToFactor(cents);
		RateTransposer rateTransposer = new RateTransposer(factor);
		WaveformSimilarityBasedOverlapAdd wsola = new WaveformSimilarityBasedOverlapAdd(Parameters.musicDefaults(factor, sampleRate));
		WaveformWriter writer = new WaveformWriter(format,target);
		AudioDispatcher dispatcher;
		if(format.getChannels() != 1){
			dispatcher = AudioDispatcherFactory.fromFile(inputFile,wsola.getInputBufferSize() * format.getChannels(),wsola.getOverlap() * format.getChannels());
			dispatcher.addAudioProcessor(new MultichannelToMono(format.getChannels(),true));
		}else{
			dispatcher = AudioDispatcherFactory.fromFile(inputFile,wsola.getInputBufferSize(),wsola.getOverlap());
		}
		wsola.setDispatcher(dispatcher);
		dispatcher.addAudioProcessor(wsola);
		dispatcher.addAudioProcessor(rateTransposer);
		dispatcher.addAudioProcessor(writer);
		dispatcher.run();

This is my android ported code:
String sourcefile = Environment.getExternalStorageDirectory().getAbsolutePath() + "/baseRec.3gpp";
		   inputFile = new File(sourcefile);
		   double sampleRate = 44100;
		   double factor = 1;
		   rateTransposer = new RateTransposer(factor);
		   wsola = new WaveformSimilarityBasedOverlapAdd(Parameters.musicDefaults(factor, sampleRate));
		   // WaveformWriter writer = new WaveformWriter(format,target);
		   
		   audioDispatcher = AudioDispatcherFactory.fromPipe(sourcefile, 44100, wsola.getInputBufferSize()*1, wsola.getOverlap()*1);
		   audioDispatcher.addAudioProcessor(new MultichannelToMono(1,true));
		   wsola.setDispatcher(audioDispatcher);
		   audioDispatcher.addAudioProcessor(wsola);
		   audioDispatcher.addAudioProcessor(rateTransposer);
		   audioDispatcher.addAudioProcessor(writer);
		   audioDispatcher.run();

Now only the problem is that i cannot resolve WaveformWriter class in android. Please guide

**Comment by JorenSix** [comment]
Hi,

There is another wave file writer that has no dependency on the JVM and works on android. See WriterProcessor.

Regards
Joren
