### ISSUE TITLE
TimeStretch on Android

### ISSUE THREAD

**Issue by ya2** [JorenSix/TarsosDSP#65]
Hello,

I'm trying to use the TimeStretch-latest.jar example, which can be found @ http://0110.be/releases/TarsosDSP/TarsosDSP-latest/TarsosDSP-latest-Examples/ with an Android project, which is being built using Eclipse .

I'm using the latest version of TarsosDSP (2.3) .

I've uncompressed TimeStretch-latest.jar, and found TimeStretch.java .
In this class, the main function, which I'm trying to make it to work in the Android project is startCli(..) .

But when I copy the code to the Android project, I don't know what to do instead of using " import javax.sound.* "

How can I make this simple Time-Stretch example to work on Android ?

Thanks .

**Comment by JorenSix** [comment]
Hi, 

You need to include `TarsosDSP-Android-latest.jar` in your android project. In Android studio this is done by placing it in the libs directory. Then you need some code like this:

    import be.tarsos.dsp.AudioDispatcher;
    import be.tarsos.dsp.GainProcessor;
    import be.tarsos.dsp.WaveformSimilarityBasedOverlapAdd;
    import be.tarsos.dsp.io.android.AndroidAudioPlayer;
    import be.tarsos.dsp.io.android.AudioDispatcherFactory;

    public void triggerLoop(String sample, double timeRatio) {
      AudioDispatcher ad = null;
      AndroidAudioPlayer ap;
      // Choose the sound
      File storageDirectory = new File(Environment.getExternalStorageDirectory(), "samples");
      String name = storageDirectory.getAbsolutePath() + "/" + sample + ".wav";
      WaveformSimilarityBasedOverlapAdd.Parameters params;
      params = WaveformSimilarityBasedOverlapAdd.Parameters.musicDefaults(timeRatio, 48000);
      WaveformSimilarityBasedOverlapAdd wsola = new WaveformSimilarityBasedOverlapAdd(params);
      ad = AudioDispatcherFactory.fromPipe(name, 48000, Math.max(5000,wsola.getInputBufferSize()), 0);
      ap = new AndroidAudioPlayer(ad.getFormat());
      ad.addAudioProcessor(wsola);
      ad.addAudioProcessor(ap);

    // Start dispatching audio data
    new Thread(ad, "Sound Thread").start();
    }

Regards

Joren

**Comment by fazalurrehmansharif** [comment]
Decoding via a pipe will not work: Could not find an ffmpeg binary for your system
