### ISSUE TITLE
IIR Bandpass Filter for Android

### ISSUE THREAD

**Issue by melancholy05** [JorenSix/TarsosDSP#68]
Hi,

Saw your project and hope it is useful to my project. 

I am trying to add a range of frequency (eg: 18k - 20k) bandpass filter to my current code. I saw that you have already created an IIRFilter and Bandpass filter. But how do I add the range ?

According to the method, I could only add 1 frequency?

 public BandPass(float freq, float bandWidth, float sampleRate)
  {
    super(freq, sampleRate);
    setBandWidth(bandWidth);
  }

How do I know what's the bandwidth too?

I am really new in this. Any tips/hints on how to use the bandpass filter on IIR is appreciated. 

Thank You so much!

**Comment by JorenSix** [comment]
Hi,

In your case the frequency would be 19kHz and bandwith 2kHz (20k-18k=2k). So it filters 2Khz centered around 19k. That is the intended functionality. Please note that the filter is not extremely steep which means that there will still be frequencies present outside the band.

**Comment by melancholy05** [comment]
Hi,

Thanks for your prompt assistance

I have done up an app which can record audio and save it into a .wav file. My next task is to add the 18k-20k bandpass filter to the code before outputting the received sound signal into a .wav file.

What should be the steps next to process the audio and get the filtered sound signal? Then I have to output the received sound signal into a .wav file. 

I saw the method public boolean process(AudioEvent audioEvent) { } in IIRFilter.java but I am not sure how to make sure of this?

Just in case, this is the code of my current android app: http://pastebin.com/Rn7BKeUz

Thanks so much for your assistance and guidance!!!

**Comment by JorenSix** [comment]
Hi, 

See the examples, you need to create an AudioDispatcher using the AudioDispatcherFactory object:

    AudioDispatcher d = AudioDispatcherFactory.formFile("audio.wav",1024,0);
    d.addAudioProcessor(new BandPassFilter(...));//filter the audio
    d.addAudioProcessor(new WaveFormWriter(...));//store the audio
    d.run();
