### ISSUE TITLE
Noise reduction as in Audacity

### ISSUE THREAD

**Issue by postacik** [JorenSix/TarsosDSP#69]
There is a noise reduction filter in Audacity.

Is it possible to perform noise reduction with this library using the existing filters in the code?

**Comment by JorenSix** [comment]
Hi,

There is no noise reduction algorithm implemented in TarsosDSP. Perhaps this could indeed be done by combining filters. If you find a working solution, please consider contributing it!

Thanks in advance

Joren

**Comment by postacik** [comment]
Thanks for the reply...
