### ISSUE TITLE
instaniating of AudioEvent

### ISSUE THREAD

**Issue by MaxGolendukhin** [JorenSix/TarsosDSP#70]
How to instaniate AudioEvent object?
I need to get fmcc of [FMCC class](https://github.com/JorenSix/TarsosDSP/blob/master/src/core/be/tarsos/dsp/mfcc/MFCC.java).
So, I have to run "process(AudioEvent audioEvent)" method of this class.
This requires to instaniate "AudioEvent " in accordance to [AudioEvent class] (https://github.com/JorenSix/TarsosDSP/blob/master/src/experimental/be/tarsos/dsp/experimental/AudioEvent.java). AudioEvent class requires to instaniate "TarsosDSPAudioFormat" object in accordance to [TarsosDSPAudioFormat class](http://0110.be/releases/TarsosDSP/TarsosDSP-2.0/TarsosDSP-2.0-Documentation/be/tarsos/dsp/io/TarsosDSPAudioFormat.html).

I did it.
```
TarsosDSPAudioFormat audioFormat = new TarsosDSPAudioFormat (8000, 16, 1, true, false);
```

Input parameters of
```
AudioEvent audioEvent = new AudioEvent(audioFormat, audioBuffer);
```
is underlined with red in Android Studio.

AudioBufeer is array of floats.

I have definitely misunderstood something and I can't get what.

Aim of project is to compare fmcc of data recieved from microphone and of saved on external storage pcm file.

I will appreciate any help.
Thanks.

**Comment by JorenSix** [comment]
Hi,

This type of construct should work. I'm not sure what is going wrong
