### ISSUE TITLE
Question: possible to get&set metadata of audio files?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [JorenSix/TarsosDSP#77]
Is it possible to get&set metadata of audio files ? I'm talkning about files that exist already.
If so, how and which file formats are supported?
If not, do you know of anyway I should do it? Any library that does it?
I need only this feature.

**Comment by JorenSix** [comment]
Hi,

TarsosDSP does not support tags/meta data. It processes the audio itself. 

I have no immediate answer but i would suggest to look for what is available in the standard Android library. Perhaps search for keywords like "reading id3 tags on android".

Regards

Joren

**Comment by AndroidDeveloperLB** [comment]
Ok, thank you.
As I remember, "id3" is only for mp3 , no? 
If so, I don't think it supports writing to it, as it's a part of the encoding process, which is written that it's not supported:
http://developer.android.com/guide/appendix/media-formats.html

Anyway, I've written about this question here:
http://stackoverflow.com/q/36473337/878126

Thank you for your time.
