### ISSUE TITLE
Broken http://tarsos.0110.be/ domain?

### ISSUE THREAD

**Issue by gradha** [JorenSix/TarsosDSP#78]
All the documentation pointed at by the readme seems to use http://tarsos.0110.be/ or 0110.be which seems inaccessible. Is this a temporal failure? Are the articles somewhere else too?

**Comment by JorenSix** [comment]
Hi,

The webserver was down. Gave it a bit of prozac, it is up again.

Since tarsos.0110.be redirects to 0110.be anyhow I have updated the readme to point directly to 0110.be. 

Thanks for bringing this to my attention.

Joren
