### ISSUE TITLE
Communicate about Java 7 mandatory

### ISSUE THREAD

**Issue by chris282** [JorenSix/TarsosDSP#89]
Hello
Thank you for this great library.

I would like to alert that this lib has been compiled with Java 7 - exactly : J2SE 7 = 51.

I tried this for example : 

```
javac -classpath TarsosDSP-2.3.jar pandora/commun/app/sound/examples/*.java

jar -cvfm Spectrogram.jar manifest.txt pandora/commun/app/sound/examples/*.class

java -jar Spectrogram.jar NIMaschineComposingaBeatPart2AddingDrums.wav

```
This resulted in an exception : 

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: be/tarsos/dsp
/pitch/PitchDetectionHandler : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:14
1)
```

As reported here : http://stackoverflow.com/questions/10382929/how-to-fix-java-lang-unsupportedclassversionerror-unsupported-major-minor-versi I understand that your lib is working with Java 7 or greater

Edit : It was my mistake as I run java with JDK 6. So this error is normal, but I think you can communicate on Java 7 mandatory :)

Thank you for the support
:)

**Comment by JorenSix** [comment]
Hi, 

To document TarsosDSP better is always a good suggestion. 

To make it more complicated the source is actually compatible with 1.6 but is compiled to 1.7 class files (version 51.0) by ant (if I remember for compatibility reasons with Android). So, you could build your own jar-files that are 1.6 (class file version 50) compatible if this is needed by changing the  

Regards

Joren
