### ISSUE TITLE
Recording while processing on Android

### ISSUE THREAD

**Issue by zofo1963** [JorenSix/TarsosDSP#91]
Hi,
Is there a way to record audio and processing at the same time ?
I've try to use MediaRecorder and PitchDetection but it doesn't work.

**Comment by leoliu1313** [comment]
Hello zofo1963,

Do you know how to get this work?

I tried different versions of JARs and even srubin/TarsosDSP, but it still crashed at either new AudioRecord() or startRecording(). Can someone help me on this?

Since I cannot simply port example projects into Android Studio, I manually copy over the example source codes to my new empty project. Hope this is the right way to do it.

Thanks,
Ching-yao

**Comment by zofo1963** [comment]
Ok resolve by myself. Works fine.
Just to had Writer as audioprocessos before PitchProcessor ;
_TarsosDSPAudioFormat format=new TarsosDSPAudioFormat(TarsosDSPAudioFormat.Encoding.PCM_SIGNED,
                22050,
                2 * 8,
                1,
                2 * 1,
                22050,
                ByteOrder.BIG_ENDIAN.equals(ByteOrder.nativeOrder()));
        File wavfile = new File(RecordDir, String.format("W%s.wav", RecordDate));
        try {
        RandomAccessFile wfile=new RandomAccessFile(wavfile,"rw");
        AudioProcessor p1 = new WriterProcessor(format,wfile);
        dispatcher.addAudioProcessor(p1);
        } catch (IOException e) {
            e.printStackTrace();
        }

        AudioProcessor p2 = new PitchProcessor(PitchProcessor.PitchEstimationAlgorithm.FFT_YIN, 22050, 1024, pdh);
        dispatcher.addAudioProcessor(p2);_

**Comment by zofo1963** [comment]
Hello,
Manifest permissions OK ?
<uses-permission android:name="android.permission.RECORD_AUDIO" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
If you just want to record use android MediaRecorder
protected void RecordStart()
    {
        String smp3File=String.format("M%s.mp4", RecordDate);
        File mp3File = new File(RecordDir,smp3File );
        String outputFile =mp3File.toString();//
Environment.getExternalStorageDirectory().getAbsolutePath() +
"/recording.3gp";;
        recorder=new MediaRecorder();
        recorder.setAudioSource(MediaRecorder.AudioSource.MIC);
        recorder.setOutputFormat(MediaRecorder.OutputFormat.MPEG_4);
        recorder.setAudioEncoder(MediaRecorder.AudioEncoder.AAC);
        try {
            recorder.setOutputFile(outputFile);
            recorder.prepare();
            recorder.start();
        }
        catch (IllegalStateException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        bStart.setEnabled(false);
        bStop.setEnabled(true);
    }

else try this :
TarsosDSPAudioFormat format=new
TarsosDSPAudioFormat(TarsosDSPAudioFormat.Encoding.PCM_SIGNED,
                22050,
                2 * 8,
                1,
                2 * 1,
                22050,
                ByteOrder.BIG_ENDIAN.equals(ByteOrder.nativeOrder()));
        File wavfile = new File(RecordDir, String.format("W%s.wav",
RecordDate));
        try {
        RandomAccessFile wfile=new RandomAccessFile(wavfile,"rw");
        AudioProcessor p1 = new WriterProcessor(format,wfile);
        dispatcher.addAudioProcessor(p1);
        } catch (IOException e) {
            e.printStackTrace();
        }
dispatcher start and stop

2016-07-14 5:01 GMT+01:00 Ching-yao Liu <notifications@github.com>:

**Comment by leoliu1313** [comment]
Hello zofo1963,
It turns out to be Manifest permissions. Thanks a lot.

**Comment by leoliu1313** [comment]
Just figured out how to import these examples correctly.
First of all, they are Eclipse projects, so don't open it in Android Studio directly.
File > New > Import Project
If this fails, try to export from Eclipse and then import again in Android Studio.

**Comment by zofo1963** [comment]
Just make copy of java sources files in Explorer and paste in a new Android
project and reference the TarsosDSP-latest.jar library.

2016-07-14 20:42 GMT+01:00 Ching-yao Liu <notifications@github.com>:

**Comment by sathishcs59** [comment]
@zofo1963  after using  your code ,i m hearing noise after recording audio in TarsosDSPAudioFormat format, Please let me know any solution to solve it
