### ISSUE TITLE
Onset Detection produces different results between Android and Java implementations

### ISSUE THREAD

**Issue by sashafrolov** [JorenSix/TarsosDSP#92]
I wrote an algorithm first on Java in Eclipse, and then ported it to Android. The only difference between the two implementations is that I used an AudioDispatcher.fromPipe call on Android as opposed to an AudioDispatcher.fromFile on my desktop. I used a buffer size of 512 and an overlap of 256 on both implementations, and I set the sample rate to 44100 (I'm pretty this is the sample rate of the .wav file I'm working with.) However, the Android implementation is detecting about 20% more onsets using the same exact algorithm. What's wrong?

**Comment by JorenSix** [comment]
Hi, 

The system must get another input, since onset detection is deterministic. Is it a mono wav file? Perhaps try to play the file to check if it is running through the pipeline correctly.

Regards Joren
