### ISSUE TITLE
Bug of function "multiply" in FFT

### ISSUE THREAD

**Issue by perfecthu** [JorenSix/TarsosDSP#97]
there is bug of function "multiply" in FFT. I have comments the buggy code and correct it.
public void multiply(float[] data, float[] other){
		assert data.length == other.length;
		if(data.length!=other.length){
			throw new IllegalArgumentException("Both arrays with imaginary numbers shouldb e of equal length");
		}
		for (int i = 1; i < data.length-1; i+=2) {
			int realIndex = i;
			int imgIndex  = i + 1;
			float tempReal = data[realIndex] * other[realIndex] + -1 *  data[imgIndex] * other[imgIndex];
			float tempImg = data[realIndex] * other[imgIndex] + data[imgIndex] * other[realIndex];
			data[realIndex] = tempReal;
			data[imgIndex] = tempImg;
			//data[realIndex] = data[realIndex] * other[realIndex] + -1 *  data[imgIndex] * other[imgIndex];
			//data[imgIndex] =  data[realIndex] * other[imgIndex] + data[imgIndex] * other[realIndex];
		}
	}

**Comment by JorenSix** [comment]
Thanks, has been fixed!
