### ISSUE TITLE
http://0110.be/ Down

### ISSUE THREAD

**Issue by Rawa** [JorenSix/TarsosDSP#98]
The website containing examples and documentation is down ( http://0110.be/ )

None of the material can be reached.

**Comment by Just-** [comment]
absolutely, me too... :(

**Comment by JorenSix** [comment]
Hi, 

0110.be is up again. The server was down.

I do not recommend cloudatcost as host. They are cheap but you get what you pay for: slow and unreliable service. I am looking for alternatives. 

Regards

Joren
